[package]
name = "url-shortener"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = {version="0", features = [ "json" ]}
rusqlite = { version = "0.34.0", features = ["bundled"] }
md5 = "0"
dotenv = "0"